runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app
# [END handlers]

libraries:
- name: flask
  version: "0.12"
- name: jinja2
  version: "2.6"
